setwd("C:/CYS/의생명통계학/기말과제_청년고용조사")
final_df<-read.csv("final_df_0613_1.csv")
#1. 주변 모형 사용. 반응변수에 대해 분포 가정 X. 
library(geepack)
#모델 돌리기
ff1<-formula(취업유무~출생연도+성별 +아이양육자+배우자월평균소득_400미만+최종학력+조사연도)
fit11<-geeglm(ff1,id=id,family=binomial,data=final_df,corstr="independence",scale.fix=TRUE)
summary(fit11)
fit22<-geeglm(ff1,id=id,family=binomial,data=final_df,corstr="exchangeable",scale.fix=TRUE)
summary(fit22)
fit33<-geeglm(ff1,id=id,family=binomial,data=final_df,corstr="ar1",scale.fix=TRUE)
summary(fit33)
fit44<-geeglm(ff1,id=id,family=binomial,data=final_df,corstr="unstructured",scale.fix=TRUE)
summary(fit44)
QIC(fit11,fit22,fit33,fit44)

#모델 돌리기
f1<-formula(취업유무~출생연도+성별 +아이양육자+배우자월평균소득_400미만+최종학력+조사연도+성별*배우자월평균소득_400미만)
fit1<-geeglm(f1,id=id,family=binomial,data=final_df,corstr="independence",scale.fix=TRUE)
summary(fit1)
fit2<-geeglm(f1,id=id,family=binomial,data=final_df,corstr="exchangeable",scale.fix=TRUE)
summary(fit2)
fit3<-geeglm(f1,id=id,family=binomial,data=final_df,corstr="ar1",scale.fix=TRUE)
summary(fit3)
fit4<-geeglm(f1,id=id,family=binomial,data=final_df,corstr="unstructured",scale.fix=TRUE)
summary(fit4)
QIC(fit1,fit2,fit3,fit4)

#모델 돌리기
ff2<-formula(취업유무~출생연도+성별+아이양육자+배우자월평균소득_400미만+최종학력+조사연도+성별*아이양육자)
fit11a<-geeglm(ff2,id=id,family=binomial,data=final_df,corstr="independence",scale.fix=TRUE)
summary(fit11a)
fit22a<-geeglm(ff2,id=id,family=binomial,data=final_df,corstr="exchangeable",scale.fix=TRUE)
summary(fit22a)
fit33a<-geeglm(ff2,id=id,family=binomial,data=final_df,corstr="ar1",scale.fix=TRUE)
summary(fit33a)
fit44a<-geeglm(ff2,id=id,family=binomial,data=final_df,corstr="unstructured",scale.fix=TRUE)
summary(fit44a)
QIC(fit11a,fit22a,fit33a,fit44a)

table(final_df$성별==1,final_df$아이양육자)
table(final_df[(final_df$성별==1)&(final_df$아이양육자==1),]$취업유무)
table(final_df[(final_df$성별==0)&(final_df$아이양육자==1),]$취업유무)
table(final_df[(final_df$성별==1)&(final_df$아이양육자==0),]$취업유무)
table(final_df[(final_df$성별==0)&(final_df$아이양육자==0),]$취업유무)
